title: Jekyll theme 'SAIFAS'
author:
  name: SAIFAS
copyright: © SAIFAS
version: 0.1.0
lang: en_US
author: SAIFAS
email: jekyll@saifas.info
about: Jekyll theme 'SAIFAS'

# Build settings

plugins:

sass:
  sass_dir: /_sass/

assets_root_path: ./assets/
assets_styles_path: ./assets/css/styles.css

social_media_facebook_handle:
social_media_facebook_url : ""

social_media_linkedin_handle:
social_media_linkedin_url : ""

social_media_twitter_handle:
social_media_twittern_url : ""

social_media_github_handle:
social_media_github_url: ""

logo: "assets/graphics/images/domain/saifas-bi/logos/saifas-brand-logo-star-theme-blue-black-276px-269px.png"
favicon: "assets/graphics/images/domain/saifas-bi/icons/fav-icons/saifas-brand-logo-star-theme-blue-black-256px-256px.ico"
