title: Jekyll theme SAIFAS
author:
  name: SAIFAS
copyright: © SAIFAS
version: 1.0.0
lang: en_US
author: SAIFAS
email: jekyll@saifas.info
about: Jekyll theme SAIFAS

gems:

sass:
  sass_dir: /_sass/

assets_root_path: /assets/
assets_styles_path: /assets/sass/styles.css